export const paths = {
  page403: '/error/403',
  page404: '/error/404',
  page500: '/error/500',
  components: '/components',
  auth: {
    signIn: (method: string) => `/auth/${method}/sign-in`,
    signUp: (method: string) => `/auth/${method}/sign-up`,
  },
  dashboard: {
    root: '/',
    user: {
      root: `/user`,
      list: `/user/list`,
      profile: `/user/profile`,
    },
    ombor: {
      root: '/ombor',
      analytics: '/ombor/analytics',
      plyonka: '/ombor/plyonka',
      kraska: '/ombor/kraska',
      suyuqKraska: '/ombor/suyuq-kraska',
      rastvaritel: '/ombor/rastvaritel',
      rastvaritelMix: '/ombor/rastvaritel-mix',
      cilindr: '/ombor/cilindr',
      kley: '/ombor/kley',
      zapchastlar: '/ombor/zapchastlar',
      otxod: '/ombor/otxod',
      finishedProductsToshkent: '/ombor/finished-products-toshkent',
      finishedProductsAngren: '/ombor/finished-products-angren',
    },
    klientlar: {
      root: '/klientlar',
      list: '/klientlar/list',
      create: '/klientlar/create',
      archived: '/klientlar/archived',
      detail: (id: string) => `/klientlar/${id}`,
      edit: (id: string) => `/klientlar/${id}/edit`,
      transactions: (id: string) => `/klientlar/${id}/transactions`,
      crm: '/klientlar/crm',
      materials: '/klientlar/materials',
      orders: '/klientlar/orders',
    },
    partners: {
      root: '/partners',
      list: '/partners/list',
      archived: '/partners/archived',
    },
    staff: {
      root: '/staff',
      list: '/staff/list',
      archived: '/staff/archived',
      crm: '/staff/crm',
      workers: '/staff/workers',
      accountants: '/staff/accountants',
      planners: '/staff/planners',
    },
    stanoklar: {
      root: '/stanoklar',
      list: '/stanoklar/list',
      archived: '/stanoklar/archived',
      pechat: '/stanoklar/pechat',
      reska: '/stanoklar/reska',
      laminatsiya: '/stanoklar/laminatsiya',
      brigades: (id: number) => `/stanoklar/${id}/brigades`,
      products: (id: number) => `/stanoklar/${id}/products`,
    },
    sushkaPaneli: {
      root: '/sushka-paneli',
    },
    finance: {
      root: '/finance',
      cash: '/finance/cash',
      transfer: '/finance/transfer',
      archived: '/finance/archived',
    },
    production: {
      root: '/production',
      reports: '/production/reports',
    },
    orderPlanning: {
      root: '/order-planning',
      inProgress: '/order-planning/in-progress',
      finished: '/order-planning/finished',
    },
    mixingStation: {
      root: '/mixing-station',
    },
    games: {
      wordBattle: {
        root: '/word-battle',
        list: '/word-battle/list',
        create: '/word-battle/create',
        edit: (id: string) => `/word-battle/${id}/edit`,
        view: `/word-battle/:id/view`,
        users: `/word-battle/players`,
        settings: `/word-battle/settings`,
      },
      flashCard: {
        root: '/flash-card',
        list: '/flash-card/list',
        create: '/flash-card/create',
        categoryList: '/flash-card/category-list',
        edit: (id: string) => `/flash-card/${id}/edit`,
      },
      picsWord: {
        root: '/pics-word',
        create: '/pics-word/create',
        update: (id: string) => `/pics-word/${id}/update`,
        list: '/pics-word/list',
        settings: '/pics-word/settings',
      },
      oddOneOut: {
        root: '/odd-one-out',
        list: '/odd-one-out/list',
        create: '/odd-one-out/create',
        edit: (id: string) => `/odd-one-out/${id}/update`,
      },
    },
  },
};
